
version: '3.8'

services:
  web:
    context: .
    dockerfile: Dockerfile
    command: gunicorn -c config/prod.py
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - /data/:/data/


