
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c config/prod.py
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - /data/:/data/


