# Generated by Django 4.0.3 on 2022-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
